# device = "cuda"
# device_ids = [ 0,]
gen_model = "g_multivanilla"
dis_model = "d_vanilla"
min_features = 32
max_features = 32
num_blocks = 5
kernel_size = 3
padding = 0
# root = "../images/balloons.png"
min_size = 25
max_size = 250
scale_factor_init = 0.75
noise_weight = 0.1
batch_size = 1
crop_size = 0
num_steps = 4000
lr = 0.0005
gen_betas = [ 0.5, 0.9,]
dis_betas = [ 0.5, 0.9,]
num_critic = 1
step_size = 2000
gamma = 0.1
penalty_weight = 0.1
reconstruction_weight = 10.0
adversarial_weight = 1.0
print_every = 200
eval_every = 100
results_dir = "./results"
# save = "2022-01-15_00-15-01"
evaluation = false
model_to_load = ""
amps_to_load = ""
use_tb = false
# save_path = "./results\\2022-01-15_00-15-01"
