# device = "cuda"
# device_ids = [ 0,]
gen_model = "g_multivanilla" # generator architecture (default: g_multivanilla)
dis_model = "d_vanilla" # discriminator architecture (default: d_vanilla)
min_features = 32 # minimum features (default: 32)
max_features = 32 # maximum features (default: 32)
num_blocks = 5
kernel_size = 3
padding = 0
# root = "../images/balloons.png"
min_size = 25 # minimum scale size
max_size = 250 # maximum scale size
scale_factor_init = 0.75 # initilize scaling factor 
noise_weight = 0.1 # noise amplitude
batch_size = 1
crop_size = 0  # cropping-size of last scale
num_steps = 4000 # number of steps per scale
lr = 0.0005 # learning rate
gen_betas = [ 0.5, 0.9,] # adam betas
dis_betas = [ 0.5, 0.9,] # adam betas
num_critic = 1 # critic iterations
step_size = 2000 # scheduler step size
gamma = 0.1 # scheduler gamma
penalty_weight = 0.1  # gradient penalty weight
reconstruction_weight = 10.0 # reconstruction-weight
adversarial_weight = 1.0
print_every = 200
eval_every = 100
# results_dir = "./results" 
# save = "2022-01-15_00-15-01" # saved folder
evaluation = false # evaluate a model
model_to_load = "" # evaluating from file
amps_to_load = "" # evaluating from file
use_tb = false # use tensorboardx 
# save_path = "./results\\2022-01-15_00-15-01"
